#!/bin/bash

set -eo pipefail

if [ -z "$1" ] || [ -z "$DATABASE_URL" ]; then
  echo "Usage: forego run ./scripts/sde-load <postgres-latest.dmp>"
  exit 1
fi

db_url_parts=$(ruby -ruri -e "URI.parse('$DATABASE_URL').tap {|u| puts \"#{u.host}:#{u.port}:#{u.user}:#{u.password}:#{u.path.tr('/','')}\" }")
db_host=$(echo $db_url_parts | awk -F: '{print $1}')
db_port=$(echo $db_url_parts | awk -F: '{print $2}')
db_user=$(echo $db_url_parts | awk -F: '{print $3}')
db_password=$(echo $db_url_parts | awk -F: '{print $4}')
db_name=$(echo $db_url_parts | awk -F: '{print $5}')

if [ -z "$db_password" ];  then
  exec env pg_restore --verbose --clean --no-acl --no-owner -d $db_name $1
else
  exec env PGPASSWORD=$db_password pg_restore --verbose --clean --no-acl --no-owner -h $db_host -U $db_user -d $db_name -p $db_port $1
fi
